pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage("Test"){
            steps {
                sh "mvn test"
                slackSend channell: 'youtubejenkins', message: 'Job started'
            }
        }

        stage("Build"){
            steps {
                sh "mvn package"
            }
        }

        stage("Deploy on Test") {
            steps {
                // deploy on container -> plugin
                deploy adapters: [tomcat9(credentialsId: 'tomcatserverdetails1', path:'',url: 'http://192.168.0.118:8080')], contextPath: '/app', war: '**/*.war'
            }
        }

        stage("Deploy on Prod") {
            input {
                message "Should we continue?"
                ok "Yes we should"
            }

            steps {
                // deploy on container -> plugin
                deploy adapters: [tomcat9(credentialsId: 'tomcatserverdetails1', path:'',url: 'http://192.168.0.118:8080')], contextPath: '/app', war: '**/*.war'
            }
        }
        
    }

    post{
        always{
            echo "============= always ============"
        }
        success{
            echo "============= pipeline executed successfully ========="
            // slackSend channel: 'youtubejenkins', message: 'Success'
        }
        failure{
            echo "============== pipeline execution failed =========="
            // slackSend channel: 'youtubejenkins', message: 'Job Failed'
        }
    }

}